# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  macos:
    runs-on: macos-11
    env:
      PACKAGENAME: bika_py37_macos_x86_64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.5.1
        pip install PySide6==6.1.3
        pip install websocket-client==0.59.0
        pip install requests==2.26.0
        pip install urllib3==1.25.11
        pip install pillow==8.3.2
        pip install Pysocks==1.7.1
        pip install https://github.com/tonquer/waifu2x-vulkan/releases/download/v1.1.1/waifu2x_vulkan-1.1.1-cp37-cp37m-macosx_10_14_x86_64.whl
        brew install create-dmg
    - name: Build
      run: |
        cd src
        cp ../res/icon/Icon.icns ./
        pyinstaller --clean --onedir --name PicACG \
            --hidden-import waifu2x_vulkan --hidden-import PySide6 --hidden-import requests \
            --hidden-import urllib3 --hidden-import websocket-client --hidden-import pillow \
            --hidden-import config \
            --hidden-import component \
            --hidden-import server \
            --hidden-import task \
            --hidden-import tools \
            --hidden-import view \
            --strip --windowed -i Icon.icns \
            start.py
        rm -rf dist/PicACG
        cp Icon.icns dist/
        ln -s /Applications/   dist/Applications
        cp -avf data dist/PicACG.app/Contents/MacOS
        xattr -cr dist/PicACG.app
        create-dmg --volname "PicACG" --volicon "Icon.icns" --icon "Icon.icns" 200 190 \
            --hide-extension "Icon.icns" ${{ env.PACKAGENAME }}.dmg dist/
        zip -9 bika.zip ${{ env.PACKAGENAME }}.dmg
        mv ${{ env.PACKAGENAME }}.dmg ..
        mv bika.zip ..
        cd ..
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: bika.zip
        retention-days: 7
        
  windows:
    runs-on: windows-latest
    env:
      PACKAGENAME: bika_py37_windows_x64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.8
        pip install pywin32==302
        pip install -r src\requirements.txt
    - name: Build
      run: |
        cd src
        cp ..\res\icon\icon.ico .\

        pyinstaller -F -w -i icon.ico start.py
        mv dist bika
        Copy-Item -Verbose -Recurse -Path data -Destination bika/
        cp ..\LICENSE bika\
        cp ..\CHANGELOG bika\
        cd ..
        mkdir ${{ env.PACKAGENAME }}
        mv src\bika ${{ env.PACKAGENAME }}
        7z a -r "$($Env:PACKAGENAME + '.zip')" "bika"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}
        retention-days: 7
        
  windows7:
    runs-on: windows-latest
    env:
      PACKAGENAME: bika_py37_windows7_x64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.5.1
        pip install pywin32==302
        pip install PySide6==6.1.3
        pip install websocket-client==0.59.0
        pip install requests==2.26.0
        pip install urllib3==1.25.11
        pip install pillow==8.3.2
        pip install Pysocks==1.7.1
        pip install waifu2x-vulkan==1.1.1
    - name: Build
      run: |
        cd src
        cp ..\res\icon\icon.ico .\
        pyinstaller -F -w -i icon.ico start.py
        mv dist bika
        Copy-Item -Verbose -Recurse -Path data -Destination bika/
        cp ..\LICENSE bika\
        cp ..\CHANGELOG bika\
        cd ..
        mkdir ${{ env.PACKAGENAME }}
        mv src\bika ${{ env.PACKAGENAME }}
        7z a -r "$($Env:PACKAGENAME + '.zip')" "bika"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}
        retention-days: 7
  
  ubuntu:
    runs-on: ubuntu-18.04
    env:
      PACKAGENAME: bika_py37_linux
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.8
        pip install https://github.com/tonquer/waifu2x-vulkan/releases/download/v1.1.1/waifu2x_vulkan-1.1.1-cp37-cp37m-linux_x86_64.whl
        pip install -r src/requirements.txt
    - name: Build
      run: |
        cd src
        pyinstaller -w start.py
        cd dist
        mkdir -p picacg.AppRun/usr/bin
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        cp -r ../../res/appimage/* picacg.AppRun/
        cp -r ../../res/icon/logo_round.png picacg.AppRun/PicACG.png
        cp -r start/* picacg.AppRun/usr/bin/
        cp -r ../data  picacg.AppRun/
        mv picacg.AppRun/usr/bin/start picacg.AppRun/usr/bin/PicACG
        chmod +x picacg.AppRun/AppRun
        chmod +x picacg.AppRun/usr/bin/PicACG
        ./appimagetool-x86_64.AppImage picacg.AppRun
        mv PicACG-x86_64.AppImage ../../${{ env.PACKAGENAME }}-x86_64.AppImage
        cd ../..
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}-x86_64.AppImage
        retention-days: 7