# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: windows-x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows:
    runs-on: windows-latest
    env:
      PACKAGENAME: bika_py37_windows_x64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Waifu2x
      run: |
        Invoke-WebRequest -Uri 'https://github.com/tonquer/waifu2x-ncnn-vulkan-python/releases/download/v1.0.2/waifu2x-ncnn-vulkan-python-v1.0.2-py37-windows-x64.zip ' -OutFile 'waifu2x-ncnn-vulkan-python-v1.0.2-py37-windows-x64.zip'
        7z x .\waifu2x-ncnn-vulkan-python-v1.0.2-py37-windows-x64.zip "-owaifu2x-ncnn-vulkan-python-v1.0.2-py37-windows-x64"
        cp waifu2x-ncnn-vulkan-python-v1.0.2-py37-windows-x64/waifu2x.pyd .\
    - name: Build
      run: |
        pyinstaller -F -i resources\icon.ico start.py --add-binary "waifu2x.pyd;."
        mv dist/start.exe "dist/start(debug).exe"
        pyinstaller -F -w -i resources\icon.ico start.py --add-binary "waifu2x.pyd;." 
        mv dist bika
        Copy-Item -Verbose -Recurse -Path data -Destination bika/
        Copy-Item -Verbose -Recurse -Path models -Destination bika/
        Copy-Item -Verbose -Recurse -Path resources -Destination bika/
        Remove-Item bika/resources/*.py -r -fo
        cp LICENSE bika\
        cp README.md bika\
        mkdir ${{ env.PACKAGENAME }}
        mv bika ${{ env.PACKAGENAME }}
        7z a -r "$($Env:PACKAGENAME + '.zip')" "bika"
    # - name: Upload
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ${{ env.PACKAGENAME }}
    #     path: ${{ env.PACKAGENAME }}
